import requests

url = "https://ymgfg.co.jp//wp-json/wp/v2/baibai"
auth = ("5rfujikawa", "XaIb D1FU oDYt ZdCe 2KKt uKsB")
headers = {"Content-Type": "application/json"}
data = {
    "title": "Your Post Title",
    "acf": {
        "property_type_baibai": "中古戸建て",
        "property_name_baibai": "rnadom",
        "present_condition_baibai": "rnadom",
        "move_in_date_baibai": "rnadom",
        "acf[price_baibai]": 12120000,
        "acf[maximum_price_baibai]": 23230000,
        "acf[img_first]": "dfd",
        "acf[img_first_caption]": "rnadom",
        "acf[img_second]": "dfd",
        "acf[img_second_caption]": "rnadom",
        "acf[img_third]": "dfd",
        "acf[img_third_caption]": "rnadom",
        "acf[img_forth]": "dfd",
        "acf[img_forth_caption]": "rnadom",
        "acf[img_fifth]": "dfd",
        "acf[img_fifth_caption]": "rnadom",
        "acf[img_sixth]": "dfd",
        "acf[img_sixth_caption]": "rnadom",
        "acf[img_seventh]": "dfd",
        "acf[img_seventh_caption]": "rnadom",
        "acf[img_eighth]": "dfd",
        "acf[img_eighth_caption]": "rnadom",
        "acf[img_ninth]": "dfd",
        "acf[img_ninth_caption]": "rnadom",
        "acf[img_tenth]": "dfd",
        "acf[img_tenth_caption]": "rnadom",
        "acf[address_baibai]": "rnadom",
        "acf[map_baibai]": "rnadom",
        "acf[access_baibai]": "rnadom",
        "acf[parking_baibai]": "rnadom",
        "acf[floor_plan_baibai]": "rnadom",
        "acf[transaction_form_baibai]": "rnadom",
        "acf[exclusive_area_baibai]": "rnadom",
        "acf[building_area_baibai]": "rnadom",
        "acf[land_area_baibai]": "rnadom",
        "acf[balcony_area_baibai]": "rnadom",
        "acf[site_area_baibai]": "rnadom",
        "acf[completion_date_baibai]": "rnadom",
        "acf[number_of_sales_baibai]": "rnadom",
        "acf[total_sales_baibai]": "rnadom",
        "acf[price_range_baibai]": "rnadom",
        "acf[direction_access_baibai]": "rnadom",
        "acf[road_conditions_baibai]": "rnadom",
        "acf[land_rights_baibai]": "rnadom",
        "acf[building_coverage_baibai]": "rnadom",
        "acf[floor_area_baibai]": "rnadom",
        "acf[enforcement_company_baibai]": "rnadom",
        "acf[use_area_baibai]": "rnadom",
        "acf[landmark_baibai]": "rnadom",
        "acf[overview_baibai]": "rnadom",
        "acf[leased_land_baibai]": False,
        "acf[period_lease_baibai]": "rnadom",
        "acf[driveway_burden_baibai]": "rnadom",
        "acf[contributions_for_roads_baibai]": "rnadom",
        "acf[other_restrictions_baibai]": "rnadom",
        "acf[notice_baibai]": "rnadom",
        "acf[info_open_date_baibai]": "rnadom",
        "acf[info_update_date_baibai]": "rnadom",
        "acf[next_date_baibai]": "rnadom",
        "acf[expiry_date_baibai]": "rnadom",
        "acf[management_fee_baibai]": "rnadom",
        "acf[repairs_cost_baibai]": "rnadom",
        "acf[management_company_baibai]": "rnadom",
        "acf[conditions_baibai]": "rnadom",
        "acf[managers_working_style_baibai]": "rnadom",
        "acf[reserve_fund_baibai]": "rnadom",
        "acf[floors_baibai]": "rnadom",
        "acf[floor_number_baibai]": "rnadom",
        "acf[seller_baibai]": "rnadom",
        "acf[development_area_baibai]": "rnadom",
        "acf[development_permit_number_baibai]": "rnadom",
        "acf[building_number_baibai]": "rnadom",
        "acf[structure_baibai]": ["sds"],
        "acf[renovation_baibai]": "rnadom",
        "acf[land_law_baibai]": "rnadom",
        "acf[city_plan_baibai]": "rnadom",
        "acf[construction_conditions_baibai]": "rnadom",
        "acf[main_lighting_baibai]": ["sdsddsd"],
        "acf[point_baibai]": "rnadom",
        "acf[movie_baibai]": "rnadom"
    },
    "status": "draft"
}

response = requests.post(url, auth=auth, headers=headers, json=data)

print(response.text)  # Or handle the response as needed
